# Generated by Django 5.1.4 on 2025-01-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_num', models.IntegerField()),
                ('second_num', models.IntegerField()),
                ('operator', models.TextField()),
                ('result', models.IntegerField()),
            ],
        ),
    ]
